publish:
	gnokey maketx addpkg \
	  -gas-fee 1ugnot \
	  -gas-wanted 20000000 \
	  -broadcast \
	  -chainid "portal-loop" \
	  -remote "https://rpc.gno.land:443" \
	  moul \
	  -pkgdir . \
	  -pkgpath gno.land/r/manfred/v3/cshijack
